-- Literature Stock: initial Supabase schema
create extension if not exists pgcrypto;

create table public.circuits (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.congregations (
  id uuid primary key default gen_random_uuid(),
  circuit_id uuid references public.circuits(id),
  name text not null,
  location text,
  language text not null default 'English',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(circuit_id,name)
);

create type public.app_role as enum ('system_admin','circuit_viewer','congregation_admin','stock_counter','viewer');
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.app_role not null default 'viewer',
  congregation_id uuid references public.congregations(id),
  circuit_id uuid references public.circuits(id),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  display_order integer not null default 0,
  active boolean not null default true
);

create table public.publications (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.categories(id),
  code text,
  title text not null,
  language text not null default 'English',
  publication_year integer,
  issue text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create type public.inventory_status as enum ('draft','in_progress','submitted','approved','reopened');
create table public.inventory_periods (
  id uuid primary key default gen_random_uuid(),
  congregation_id uuid not null references public.congregations(id),
  year integer not null check (year between 2000 and 2100),
  month integer not null check (month between 1 and 12),
  status public.inventory_status not null default 'draft',
  opened_at timestamptz default now(),
  submitted_at timestamptz,
  submitted_by uuid references public.profiles(id),
  unique(congregation_id,year,month)
);

create table public.stock_counts (
  id uuid primary key default gen_random_uuid(),
  inventory_period_id uuid not null references public.inventory_periods(id) on delete cascade,
  publication_id uuid not null references public.publications(id),
  expected_quantity integer not null default 0 check(expected_quantity >= 0),
  physical_quantity integer not null default 0 check(physical_quantity >= 0),
  verified boolean not null default false,
  remarks text,
  counted_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  unique(inventory_period_id,publication_id)
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  action text not null,
  record_type text not null,
  record_id text,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.congregations enable row level security;
alter table public.inventory_periods enable row level security;
alter table public.stock_counts enable row level security;

-- Starter policy: authenticated users can read reference data.
create policy "authenticated read congregations" on public.congregations for select to authenticated using (true);
create policy "users read own profile" on public.profiles for select to authenticated using (id = auth.uid());

-- Add role-scoped write policies after creating the first system administrator.
