'use client';

import { useEffect, useMemo, useState } from 'react';

type Page='dashboard'|'stock'|'reports'|'congregations'|'publications'|'users'|'settings';
type Count={physical:number;verified:boolean};
type Category={id:string;name:string};
type Publication={id:string;categoryId:string;code:string;title:string;opening:number};

type Congregation={id:string;name:string;status:'Submitted'|'In progress'};

const categories:Category[]=[
{id:'bibles',name:'Bibles'},{id:'books',name:'Books'},{id:'brochures',name:'Brochures and Booklets'},
{id:'tracts',name:'Tracts'},{id:'magazines',name:'Public Magazines'},{id:'watchtower',name:'Study Watchtower'},
{id:'workbooks',name:'Meeting Workbooks'},{id:'daily',name:'Examining the Scriptures Daily'},{id:'forms',name:'Forms and Supplies'}
];

const publications:Publication[]=[
{id:'nwt',categoryId:'bibles',code:'nwt',title:'New World Translation',opening:8},{id:'nwtpkt',categoryId:'bibles',code:'nwtpkt',title:'New World Translation (pocket-size)',opening:0},{id:'b-other',categoryId:'bibles',code:'',title:'Others',opening:0},
{id:'be',categoryId:'books',code:'be',title:'Ministry School',opening:0},{id:'bhs',categoryId:'books',code:'bhs',title:'Teach Us',opening:0},{id:'cf',categoryId:'books',code:'cf',title:'My Follower',opening:0},{id:'cl',categoryId:'books',code:'cl',title:'Close to Jehovah',opening:0},{id:'ia',categoryId:'books',code:'ia',title:'Imitate',opening:0},{id:'jy',categoryId:'books',code:'jy',title:'Jesus—The Way',opening:0},{id:'kr',categoryId:'books',code:'kr',title:"God's Kingdom Rules!",opening:0},{id:'lfb',categoryId:'books',code:'lfb',title:'Learn From the Bible',opening:1},{id:'lff',categoryId:'books',code:'lff',title:'Enjoy Life Forever! (Book)',opening:0},{id:'lr',categoryId:'books',code:'lr',title:'Teacher',opening:0},{id:'od',categoryId:'books',code:'od',title:'Organized',opening:16},{id:'rr',categoryId:'books',code:'rr',title:'Pure Worship',opening:0},{id:'scl',categoryId:'books',code:'scl',title:'Scriptures for Christian Living',opening:31},{id:'sjj',categoryId:'books',code:'sjj',title:'Sing Out Joyfully',opening:16},{id:'sjjyls',categoryId:'books',code:'sjjyls',title:'Sing Out Joyfully—Lyrics Only',opening:0},{id:'yp1',categoryId:'books',code:'yp1',title:'Young People Ask, Volume 1',opening:0},{id:'yp2',categoryId:'books',code:'yp2',title:'Young People Ask, Volume 2',opening:1},{id:'book-other',categoryId:'books',code:'',title:'Others',opening:31},
{id:'ay',categoryId:'brochures',code:'ay',title:'Reading and Writing',opening:0},{id:'fg',categoryId:'brochures',code:'fg',title:'Good News',opening:0},{id:'hf',categoryId:'brochures',code:'hf',title:'Happy Family',opening:0},{id:'lc',categoryId:'brochures',code:'lc',title:'Was Life Created?',opening:0},{id:'ld',categoryId:'brochures',code:'ld',title:'Listen to God',opening:26},{id:'lf',categoryId:'brochures',code:'lf',title:'Origin of Life',opening:0},{id:'lffi',categoryId:'brochures',code:'lffi',title:'Enjoy Life Forever! (Brochure)',opening:0},{id:'ll',categoryId:'brochures',code:'ll',title:'Listen and Live',opening:68},{id:'lmd',categoryId:'brochures',code:'lmd',title:'Love People',opening:23},{id:'mb',categoryId:'brochures',code:'mb',title:'My Bible Lessons',opening:0},{id:'ol',categoryId:'brochures',code:'ol',title:'Road to Life',opening:0},{id:'rj',categoryId:'brochures',code:'rj',title:'Return to Jehovah',opening:0},{id:'sp',categoryId:'brochures',code:'sp',title:'Spirits of the Dead',opening:0},{id:'th',categoryId:'brochures',code:'th',title:'Teaching',opening:0},{id:'ypq',categoryId:'brochures',code:'ypq',title:'10 Questions',opening:0},{id:'bro-other',categoryId:'brochures',code:'',title:'Others',opening:0},
{id:'inv',categoryId:'tracts',code:'inv',title:'Invitation to Congregation Meetings',opening:0},{id:'t30',categoryId:'tracts',code:'T-30',title:'View the Bible (T-30)',opening:698},{id:'t31',categoryId:'tracts',code:'T-31',title:'View the Future (T-31)',opening:332},{id:'t32',categoryId:'tracts',code:'T-32',title:'Happy Family Life (Tract No. 32)',opening:89},{id:'t33',categoryId:'tracts',code:'T-33',title:'Who Controls the World? (T-33)',opening:8},{id:'t34',categoryId:'tracts',code:'T-34',title:'Will Suffering End? (T-34)',opening:361},{id:'t35',categoryId:'tracts',code:'T-35',title:'Live Again (T-35)',opening:526},{id:'t36',categoryId:'tracts',code:'T-36',title:'Kingdom (T-36)',opening:461},{id:'tract-other',categoryId:'tracts',code:'',title:'Others',opening:0},
...['g18.1','g18.2','g18.3','g19.1','g19.2','g19.3','g20.1','g20.2','g20.3','g21.1','g21.2','g21.3','g22.1','g23.1','g24.1','g25.1'].map((code,i)=>({id:code,categoryId:'magazines',code,title:'Awake!',opening:code==='g18.2'?48:0})),
...['wp18.1','wp18.2','wp18.3','wp19.1','wp19.2','wp19.3','wp20.1','wp20.2','wp20.3','wp21.1','wp21.2','wp21.3','wp22.1','wp23.1','wp24.1','wp25.1'].map(code=>({id:code,categoryId:'magazines',code,title:'Watchtower (Public)',opening:code==='wp20.3'?112:0})),
{id:'mag-other',categoryId:'magazines',code:'',title:'Others',opening:0},
{id:'wt-apr',categoryId:'watchtower',code:'w26.04',title:'Watchtower — April 2026',opening:21},{id:'wt-may',categoryId:'watchtower',code:'w26.05',title:'Watchtower — May 2026',opening:23},{id:'wt-jun',categoryId:'watchtower',code:'w26.06',title:'Watchtower — June 2026',opening:260},{id:'wt-jul',categoryId:'watchtower',code:'w26.07',title:'Watchtower — July 2026',opening:300},{id:'wt-other',categoryId:'watchtower',code:'',title:'Others',opening:0},
{id:'mw-janfeb',categoryId:'workbooks',code:'mwb26.01',title:'January–February 2026',opening:40},{id:'mw-marapr',categoryId:'workbooks',code:'mwb26.03',title:'March–April 2026',opening:3},{id:'mw-julaug',categoryId:'workbooks',code:'mwb26.07',title:'July–August 2026',opening:16},{id:'mw-sepoct',categoryId:'workbooks',code:'mwb26.09',title:'September–October 2026',opening:271},{id:'mw-other',categoryId:'workbooks',code:'',title:'Others',opening:0},
{id:'esd26',categoryId:'daily',code:'es26',title:'Examining the Scriptures Daily — 2026',opening:2},{id:'esd20',categoryId:'daily',code:'es20',title:'Examining the Scriptures Daily — 2020',opening:1},{id:'daily-other',categoryId:'daily',code:'',title:'Others',opening:0},
{id:'jwcd4',categoryId:'forms',code:'jwcd4',title:'Contact card for jw.org',opening:7},{id:'jwcd9',categoryId:'forms',code:'jwcd9',title:'Contact card for free Bible course',opening:7},{id:'s4',categoryId:'forms',code:'S-4',title:'Field Service Report',opening:0},{id:'s24',categoryId:'forms',code:'S-24',title:'Transaction Record',opening:500},{id:'forms-other',categoryId:'forms',code:'',title:'Others',opening:0}
];

const congregations:Congregation[]=[{id:'combined',name:'Long Ridge / Mapepe & Chilanga Central',status:'Submitted'},{id:'kabulonga',name:'Kabulonga',status:'In progress'},{id:'matero',name:'Matero',status:'In progress'}];
const nav:[Page,string][]=[['dashboard','Dashboard'],['stock','Stock Count'],['reports','Reports'],['congregations','Congregations'],['publications','Publications'],['users','Users'],['settings','Settings']];

export default function HomePage(){
 const [page,setPage]=useState<Page>('dashboard');
 const [congregationId,setCongregationId]=useState('combined');
 const [step,setStep]=useState(0);
 const [review,setReview]=useState(false);
 const [counts,setCounts]=useState<Record<string,Count>>({});
 const congregation=congregations.find(c=>c.id===congregationId)!;
 useEffect(()=>{const saved=localStorage.getItem('lms-counts-v2');if(saved)setCounts(JSON.parse(saved))},[]);
 useEffect(()=>{localStorage.setItem('lms-counts-v2',JSON.stringify(counts))},[counts]);
 const getCount=(p:Publication)=>counts[`${congregationId}|${p.id}`]||{physical:p.opening,verified:false};
 const setCount=(p:Publication,patch:Partial<Count>)=>setCounts(v=>({...v,[`${congregationId}|${p.id}`]:{...getCount(p),...patch}}));
 const stats=useMemo(()=>{const values=publications.map(getCount);return{total:values.reduce((a,b)=>a+b.physical,0),verified:values.filter(v=>v.verified).length}},[counts,congregationId]);
 const currentCategory=categories[step];
 const currentItems=publications.filter(p=>p.categoryId===currentCategory?.id);
 const startStock=(categoryIndex=0)=>{setPage('stock');setReview(false);setStep(categoryIndex)};
 const markAll=()=>currentItems.forEach(p=>setCount(p,{verified:true}));
 const next=()=>{if(step<categories.length-1)setStep(step+1);else setReview(true)};
 const previous=()=>{if(review)setReview(false);else if(step>0)setStep(step-1);else setPage('dashboard')};

 return <div className="appShell">
  <aside className="sidebar"><div className="brand"><span>LMS</span><div><strong>Literature Stock</strong><small>Management System</small></div></div><nav>{nav.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);if(id==='stock'){setReview(false);setStep(0)}}}>{label}</button>)}</nav><small className="version">August 2026</small></aside>
  <main className="workspace">
   <header className="topbar"><div><p>August 2026</p><h1>{page==='stock'?(review?'Review and Submit':currentCategory.name):nav.find(x=>x[0]===page)?.[1]}</h1></div><select value={congregationId} onChange={e=>setCongregationId(e.target.value)}>{congregations.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></header>

   {page==='dashboard'&&<><section className="stats"><article><span>Total publications</span><strong>{publications.length}</strong></article><article><span>Physical stock</span><strong>{stats.total.toLocaleString()}</strong></article><article><span>Items verified</span><strong>{stats.verified}/{publications.length}</strong></article><article><span>Congregations submitted</span><strong>1/{congregations.length}</strong></article></section><section className="dashboardGrid"><section className="panel"><div className="panelHead"><div><h2>Literature categories</h2><p>Open a category to capture stock quantities.</p></div><button onClick={()=>startStock(0)}>Start stock count</button></div><div className="categoryGrid">{categories.map((c,i)=>{const items=publications.filter(p=>p.categoryId===c.id);const done=items.filter(p=>getCount(p).verified).length;return <button key={c.id} onClick={()=>startStock(i)}><strong>{c.name}</strong><span>{done} of {items.length} verified</span><i style={{width:`${items.length?Math.round(done/items.length*100):0}%`}}/></button>})}</div></section><aside className="submissionPanel"><h2>Submission status</h2><p>Congregations for the selected period.</p>{congregations.map(c=><article key={c.id}><div><strong>{c.name}</strong><span>August 2026</span></div><em className={c.status==='Submitted'?'submitted':'progress'}>{c.status}</em></article>)}</aside></section></>}

   {page==='stock'&&!review&&<section className="countScreen"><div className="countIntro"><span>AUGUST 2026 | ENGLISH</span><h2>{currentCategory.name}</h2><p>Select an item to update the quantity. Mark the item as done after it has been updated or verified.</p><button onClick={markAll}>✓ Mark All Items Done</button></div><div className="countCards">{currentItems.map(p=>{const c=getCount(p);return <article key={p.id}><button className="pubName" onClick={()=>{const value=prompt(`Enter quantity for ${p.title}`,String(c.physical));if(value!==null&&!Number.isNaN(Number(value)))setCount(p,{physical:Math.max(0,Number(value)),verified:false})}}>{p.code?`(${p.code}) `:''}{p.title}</button><div className="countRow"><strong>{c.physical}</strong><label>Done <input type="checkbox" checked={c.verified} onChange={e=>setCount(p,{verified:e.target.checked})}/><span/></label></div></article>})}</div><div className="wizardActions"><button className="secondary" onClick={previous}>Previous</button><button onClick={next}>{step===categories.length-1?'Review':'Next'}</button></div></section>}

   {page==='stock'&&review&&<section className="reviewScreen"><div className="countIntro"><span>AUGUST 2026 | ENGLISH</span><h2>Review and Submit</h2><p>Confirm that the following quantities are correct and submit.</p></div>{categories.map(cat=>{const items=publications.filter(p=>p.categoryId===cat.id&&getCount(p).physical>0);if(!items.length)return null;return <section className="reviewGroup" key={cat.id}><h3>{cat.name}</h3>{items.map(p=><div key={p.id}><span>{p.code?`(${p.code}) `:''}{p.title}</span><strong>{getCount(p).physical}</strong></div>)}</section>})}<p className="submitNote">ⓘ The report can be submitted after the end of the month.</p><div className="wizardActions"><button className="secondary" onClick={previous}>Previous</button><button onClick={()=>alert('Stock count submitted successfully.')}>Submit</button></div></section>}

   {page==='reports'&&<section className="panel"><div className="panelHead"><div><h2>August stock report</h2><p>{congregation.name}</p></div></div><table><thead><tr><th>Category</th><th>Items</th><th>Total stock</th></tr></thead><tbody>{categories.map(cat=>{const items=publications.filter(p=>p.categoryId===cat.id);return <tr key={cat.id}><td>{cat.name}</td><td>{items.length}</td><td>{items.reduce((s,p)=>s+getCount(p).physical,0).toLocaleString()}</td></tr>})}</tbody></table></section>}
   {page==='congregations'&&<section className="panel"><div className="panelHead"><div><h2>Congregations</h2><p>Manage congregations without changing the dashboard layout.</p></div><button onClick={()=>alert('Supabase-backed add congregation is the next database step.')}>Add congregation</button></div><div className="simpleList">{congregations.map(c=><article key={c.id}><div><strong>{c.name}</strong><span>{c.status}</span></div><div className="rowActions"><button>Edit</button><button>Deactivate</button></div></article>)}</div></section>}
   {page==='publications'&&<section className="panel"><div className="panelHead"><div><h2>Categories and publications</h2><p>Add or maintain publications under the approved categories.</p></div><div className="headerActions"><button>Add category</button><button>Add publication</button></div></div><div className="simpleList">{categories.map(c=><article key={c.id}><div><strong>{c.name}</strong><span>{publications.filter(p=>p.categoryId===c.id).length} publications</span></div><div className="rowActions"><button>Edit</button><button>Deactivate</button></div></article>)}</div></section>}
   {page==='users'&&<section className="panel"><div className="emptyState">User administration will use Supabase Authentication.</div></section>}
   {page==='settings'&&<section className="panel"><div className="simpleList"><article><strong>Current period</strong><span>August 2026</span></article><article><strong>Language</strong><span>English</span></article></div></section>}
  </main>
 </div>
}
