-- Seed the approved publication catalogue used by the application.
-- Safe to run repeatedly: existing publication keys are updated, not duplicated.

insert into public.publications (
  publication_key,
  category_key,
  publication_code,
  title,
  language,
  issue_label,
  opening_quantity,
  display_order,
  active
) values
  ('nwt', 'bibles', 'nwt', 'New World Translation', 'English', null, 8, 1, true),
  ('nwtpkt', 'bibles', 'nwtpkt', 'New World Translation (pocket-size)', 'English', null, 0, 2, true),
  ('b-other', 'bibles', null, 'Others', 'English', null, 0, 3, true),
  ('be', 'books', 'be', 'Ministry School', 'English', null, 0, 4, true),
  ('bhs', 'books', 'bhs', 'Teach Us', 'English', null, 0, 5, true),
  ('cf', 'books', 'cf', 'My Follower', 'English', null, 0, 6, true),
  ('cl', 'books', 'cl', 'Close to Jehovah', 'English', null, 0, 7, true),
  ('ia', 'books', 'ia', 'Imitate', 'English', null, 0, 8, true),
  ('jy', 'books', 'jy', 'Jesus—The Way', 'English', null, 0, 9, true),
  ('kr', 'books', 'kr', 'God''s Kingdom Rules!', 'English', null, 0, 10, true),
  ('lfb', 'books', 'lfb', 'Learn From the Bible', 'English', null, 1, 11, true),
  ('lff', 'books', 'lff', 'Enjoy Life Forever! (Book)', 'English', null, 0, 12, true),
  ('lr', 'books', 'lr', 'Teacher', 'English', null, 0, 13, true),
  ('od', 'books', 'od', 'Organized', 'English', null, 16, 14, true),
  ('rr', 'books', 'rr', 'Pure Worship', 'English', null, 0, 15, true),
  ('scl', 'books', 'scl', 'Scriptures for Christian Living', 'English', null, 31, 16, true),
  ('sjj', 'books', 'sjj', 'Sing Out Joyfully', 'English', null, 16, 17, true),
  ('sjjyls', 'books', 'sjjyls', 'Sing Out Joyfully—Lyrics Only', 'English', null, 0, 18, true),
  ('yp1', 'books', 'yp1', 'Young People Ask, Volume 1', 'English', null, 0, 19, true),
  ('yp2', 'books', 'yp2', 'Young People Ask, Volume 2', 'English', null, 1, 20, true),
  ('book-other', 'books', null, 'Others', 'English', null, 31, 21, true),
  ('ay', 'brochures', 'ay', 'Reading and Writing', 'English', null, 0, 22, true),
  ('fg', 'brochures', 'fg', 'Good News', 'English', null, 0, 23, true),
  ('hf', 'brochures', 'hf', 'Happy Family', 'English', null, 0, 24, true),
  ('lc', 'brochures', 'lc', 'Was Life Created?', 'English', null, 0, 25, true),
  ('ld', 'brochures', 'ld', 'Listen to God', 'English', null, 26, 26, true),
  ('lf', 'brochures', 'lf', 'Origin of Life', 'English', null, 0, 27, true),
  ('lffi', 'brochures', 'lffi', 'Enjoy Life Forever! (Brochure)', 'English', null, 0, 28, true),
  ('ll', 'brochures', 'll', 'Listen and Live', 'English', null, 68, 29, true),
  ('lmd', 'brochures', 'lmd', 'Love People', 'English', null, 23, 30, true),
  ('mb', 'brochures', 'mb', 'My Bible Lessons', 'English', null, 0, 31, true),
  ('ol', 'brochures', 'ol', 'Road to Life', 'English', null, 0, 32, true),
  ('rj', 'brochures', 'rj', 'Return to Jehovah', 'English', null, 0, 33, true),
  ('sp', 'brochures', 'sp', 'Spirits of the Dead', 'English', null, 0, 34, true),
  ('th', 'brochures', 'th', 'Teaching', 'English', null, 0, 35, true),
  ('ypq', 'brochures', 'ypq', '10 Questions', 'English', null, 0, 36, true),
  ('bro-other', 'brochures', null, 'Others', 'English', null, 0, 37, true),
  ('inv', 'tracts', 'inv', 'Invitation to Congregation Meetings', 'English', null, 0, 38, true),
  ('t30', 'tracts', 'T-30', 'View the Bible (T-30)', 'English', null, 698, 39, true),
  ('t31', 'tracts', 'T-31', 'View the Future (T-31)', 'English', null, 332, 40, true),
  ('t32', 'tracts', 'T-32', 'Happy Family Life (Tract No. 32)', 'English', null, 89, 41, true),
  ('t33', 'tracts', 'T-33', 'Who Controls the World? (T-33)', 'English', null, 8, 42, true),
  ('t34', 'tracts', 'T-34', 'Will Suffering End? (T-34)', 'English', null, 361, 43, true),
  ('t35', 'tracts', 'T-35', 'Live Again (T-35)', 'English', null, 526, 44, true),
  ('t36', 'tracts', 'T-36', 'Kingdom (T-36)', 'English', null, 461, 45, true),
  ('tract-other', 'tracts', null, 'Others', 'English', null, 0, 46, true),
  ('g18.1', 'magazines', 'g18.1', 'Awake!', 'English', 'g18.1', 0, 47, true),
  ('g18.2', 'magazines', 'g18.2', 'Awake!', 'English', 'g18.2', 48, 48, true),
  ('g18.3', 'magazines', 'g18.3', 'Awake!', 'English', 'g18.3', 0, 49, true),
  ('g19.1', 'magazines', 'g19.1', 'Awake!', 'English', 'g19.1', 0, 50, true),
  ('g19.2', 'magazines', 'g19.2', 'Awake!', 'English', 'g19.2', 0, 51, true),
  ('g19.3', 'magazines', 'g19.3', 'Awake!', 'English', 'g19.3', 0, 52, true),
  ('g20.1', 'magazines', 'g20.1', 'Awake!', 'English', 'g20.1', 0, 53, true),
  ('g20.2', 'magazines', 'g20.2', 'Awake!', 'English', 'g20.2', 0, 54, true),
  ('g20.3', 'magazines', 'g20.3', 'Awake!', 'English', 'g20.3', 0, 55, true),
  ('g21.1', 'magazines', 'g21.1', 'Awake!', 'English', 'g21.1', 0, 56, true),
  ('g21.2', 'magazines', 'g21.2', 'Awake!', 'English', 'g21.2', 0, 57, true),
  ('g21.3', 'magazines', 'g21.3', 'Awake!', 'English', 'g21.3', 0, 58, true),
  ('g22.1', 'magazines', 'g22.1', 'Awake!', 'English', 'g22.1', 0, 59, true),
  ('g23.1', 'magazines', 'g23.1', 'Awake!', 'English', 'g23.1', 0, 60, true),
  ('g24.1', 'magazines', 'g24.1', 'Awake!', 'English', 'g24.1', 0, 61, true),
  ('g25.1', 'magazines', 'g25.1', 'Awake!', 'English', 'g25.1', 0, 62, true),
  ('wp18.1', 'magazines', 'wp18.1', 'Watchtower (Public)', 'English', 'wp18.1', 0, 63, true),
  ('wp18.2', 'magazines', 'wp18.2', 'Watchtower (Public)', 'English', 'wp18.2', 0, 64, true),
  ('wp18.3', 'magazines', 'wp18.3', 'Watchtower (Public)', 'English', 'wp18.3', 0, 65, true),
  ('wp19.1', 'magazines', 'wp19.1', 'Watchtower (Public)', 'English', 'wp19.1', 0, 66, true),
  ('wp19.2', 'magazines', 'wp19.2', 'Watchtower (Public)', 'English', 'wp19.2', 0, 67, true),
  ('wp19.3', 'magazines', 'wp19.3', 'Watchtower (Public)', 'English', 'wp19.3', 0, 68, true),
  ('wp20.1', 'magazines', 'wp20.1', 'Watchtower (Public)', 'English', 'wp20.1', 0, 69, true),
  ('wp20.2', 'magazines', 'wp20.2', 'Watchtower (Public)', 'English', 'wp20.2', 0, 70, true),
  ('wp20.3', 'magazines', 'wp20.3', 'Watchtower (Public)', 'English', 'wp20.3', 112, 71, true),
  ('wp21.1', 'magazines', 'wp21.1', 'Watchtower (Public)', 'English', 'wp21.1', 0, 72, true),
  ('wp21.2', 'magazines', 'wp21.2', 'Watchtower (Public)', 'English', 'wp21.2', 0, 73, true),
  ('wp21.3', 'magazines', 'wp21.3', 'Watchtower (Public)', 'English', 'wp21.3', 0, 74, true),
  ('wp22.1', 'magazines', 'wp22.1', 'Watchtower (Public)', 'English', 'wp22.1', 0, 75, true),
  ('wp23.1', 'magazines', 'wp23.1', 'Watchtower (Public)', 'English', 'wp23.1', 0, 76, true),
  ('wp24.1', 'magazines', 'wp24.1', 'Watchtower (Public)', 'English', 'wp24.1', 0, 77, true),
  ('wp25.1', 'magazines', 'wp25.1', 'Watchtower (Public)', 'English', 'wp25.1', 0, 78, true),
  ('mag-other', 'magazines', null, 'Others', 'English', null, 0, 79, true),
  ('wt-apr', 'watchtower', 'w26.04', 'Watchtower — April 2026', 'English', null, 21, 80, true),
  ('wt-may', 'watchtower', 'w26.05', 'Watchtower — May 2026', 'English', null, 23, 81, true),
  ('wt-jun', 'watchtower', 'w26.06', 'Watchtower — June 2026', 'English', null, 260, 82, true),
  ('wt-jul', 'watchtower', 'w26.07', 'Watchtower — July 2026', 'English', null, 300, 83, true),
  ('wt-other', 'watchtower', null, 'Others', 'English', null, 0, 84, true),
  ('mw-janfeb', 'workbooks', 'mwb26.01', 'January–February 2026', 'English', null, 40, 85, true),
  ('mw-marapr', 'workbooks', 'mwb26.03', 'March–April 2026', 'English', null, 3, 86, true),
  ('mw-julaug', 'workbooks', 'mwb26.07', 'July–August 2026', 'English', null, 16, 87, true),
  ('mw-sepoct', 'workbooks', 'mwb26.09', 'September–October 2026', 'English', null, 271, 88, true),
  ('mw-other', 'workbooks', null, 'Others', 'English', null, 0, 89, true),
  ('esd26', 'daily', 'es26', 'Examining the Scriptures Daily — 2026', 'English', null, 2, 90, true),
  ('esd20', 'daily', 'es20', 'Examining the Scriptures Daily — 2020', 'English', null, 1, 91, true),
  ('daily-other', 'daily', null, 'Others', 'English', null, 0, 92, true),
  ('jwcd4', 'forms', 'jwcd4', 'Contact card for jw.org', 'English', null, 7, 93, true),
  ('jwcd9', 'forms', 'jwcd9', 'Contact card for free Bible course', 'English', null, 7, 94, true),
  ('s4', 'forms', 'S-4', 'Field Service Report', 'English', null, 0, 95, true),
  ('s24', 'forms', 'S-24', 'Transaction Record', 'English', null, 500, 96, true),
  ('forms-other', 'forms', null, 'Others', 'English', null, 0, 97, true)
on conflict (publication_key) do update set
  category_key = excluded.category_key,
  publication_code = excluded.publication_code,
  title = excluded.title,
  language = excluded.language,
  issue_label = excluded.issue_label,
  opening_quantity = excluded.opening_quantity,
  display_order = excluded.display_order,
  active = excluded.active,
  updated_at = now();

select category_key, count(*) as publication_count
from public.publications
where active = true
group by category_key
order by category_key;

select count(*) as total_publications
from public.publications
where active = true;

notify pgrst, 'reload schema';
